// <auto-generated />
using System;
using HowTo.DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HowTo.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230615141319_AddInteractive")]
    partial class AddInteractive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("HowTo.Entities.Article.ArticleDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CourseDtoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CourseDtoId");

                    b.ToTable("ArticleContext");
                });

            modelBuilder.Entity("HowTo.Entities.Contributor.ContributorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContributorEntityContext");
                });

            modelBuilder.Entity("HowTo.Entities.Course.CourseDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CourseContext");
                });

            modelBuilder.Entity("HowTo.Entities.Interactives.CheckList.CheckListDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClausesJsonStringArray")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InteractiveId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InteractiveId");

                    b.ToTable("CheckListContext");
                });

            modelBuilder.Entity("HowTo.Entities.Interactives.ChoiseOfAnswers.ChoiceOfAnswerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnswersJsonBoolArray")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InteractiveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionsJsonStringArray")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InteractiveId");

                    b.ToTable("ChoiceOfAnswerContext");
                });

            modelBuilder.Entity("HowTo.Entities.Interactives.ChoiseOfAnswers.LogChoiceOfAnswerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnswersJsonBoolArray")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogChoiceOfAnswerContext");
                });

            modelBuilder.Entity("HowTo.Entities.Interactives.InteractiveDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InteractiveContext");
                });

            modelBuilder.Entity("HowTo.Entities.Interactives.ProgramWriting.LogProgramWritingDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogProgramWritingContext");
                });

            modelBuilder.Entity("HowTo.Entities.Interactives.ProgramWriting.ProgramWritingDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeExample")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InteractiveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InteractiveId");

                    b.ToTable("ProgramWritingContext");
                });

            modelBuilder.Entity("HowTo.Entities.Interactives.WritingOfAnswer.LogWritingOfAnswerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogWritingOfAnswerContext");
                });

            modelBuilder.Entity("HowTo.Entities.Interactives.WritingOfAnswer.WritingOfAnswerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InteractiveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InteractiveId");

                    b.ToTable("WritingOfAnswerContext");
                });

            modelBuilder.Entity("HowTo.Entities.UserInfo.LastInteractiveInfo.LastCheckListDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CheckedClausesJsonBoolArray")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserUniqueInfoDtoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserUniqueInfoDtoId");

                    b.ToTable("LastCheckListContext");
                });

            modelBuilder.Entity("HowTo.Entities.UserInfo.LastInteractiveInfo.LastChoiceOfAnswerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnswersJsonBoolArray")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserUniqueInfoDtoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserUniqueInfoDtoId");

                    b.ToTable("LastChoiceOfAnswerContext");
                });

            modelBuilder.Entity("HowTo.Entities.UserInfo.LastInteractiveInfo.LastProgramWritingDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserUniqueInfoDtoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserUniqueInfoDtoId");

                    b.ToTable("LastProgramWritingContext");
                });

            modelBuilder.Entity("HowTo.Entities.UserInfo.LastInteractiveInfo.LastWritingOfAnswerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserUniqueInfoDtoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserUniqueInfoDtoId");

                    b.ToTable("LastWritingOfAnswerContext");
                });

            modelBuilder.Entity("HowTo.Entities.UserInfo.UserUniqueInfoDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastReadCourseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserUniqueInfoContext");
                });

            modelBuilder.Entity("HowTo.Entities.ViewedEntity.ViewedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserUniqueInfoDtoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserUniqueInfoDtoId");

                    b.ToTable("UserViewEntityContext");
                });

            modelBuilder.Entity("HowTo.Entities.Views.UserGuid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ViewDtoArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ViewDtoCourseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ViewDtoCourseId", "ViewDtoArticleId");

                    b.ToTable("UserGuid");
                });

            modelBuilder.Entity("HowTo.Entities.Views.ViewDto", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "ArticleId");

                    b.ToTable("ViewContext");
                });

            modelBuilder.Entity("HowTo.Entities.Article.ArticleDto", b =>
                {
                    b.HasOne("HowTo.Entities.Contributor.ContributorEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HowTo.Entities.Course.CourseDto", null)
                        .WithMany("Articles")
                        .HasForeignKey("CourseDtoId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("HowTo.Entities.Interactives.CheckList.CheckListDto", b =>
                {
                    b.HasOne("HowTo.Entities.Interactives.InteractiveDto", "Interactive")
                        .WithMany()
                        .HasForeignKey("InteractiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interactive");
                });

            modelBuilder.Entity("HowTo.Entities.Interactives.ChoiseOfAnswers.ChoiceOfAnswerDto", b =>
                {
                    b.HasOne("HowTo.Entities.Interactives.InteractiveDto", "Interactive")
                        .WithMany()
                        .HasForeignKey("InteractiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interactive");
                });

            modelBuilder.Entity("HowTo.Entities.Interactives.ProgramWriting.ProgramWritingDto", b =>
                {
                    b.HasOne("HowTo.Entities.Interactives.InteractiveDto", "Interactive")
                        .WithMany()
                        .HasForeignKey("InteractiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interactive");
                });

            modelBuilder.Entity("HowTo.Entities.Interactives.WritingOfAnswer.WritingOfAnswerDto", b =>
                {
                    b.HasOne("HowTo.Entities.Interactives.InteractiveDto", "Interactive")
                        .WithMany()
                        .HasForeignKey("InteractiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interactive");
                });

            modelBuilder.Entity("HowTo.Entities.UserInfo.LastInteractiveInfo.LastCheckListDto", b =>
                {
                    b.HasOne("HowTo.Entities.UserInfo.UserUniqueInfoDto", null)
                        .WithMany("LastCheckLists")
                        .HasForeignKey("UserUniqueInfoDtoId");
                });

            modelBuilder.Entity("HowTo.Entities.UserInfo.LastInteractiveInfo.LastChoiceOfAnswerDto", b =>
                {
                    b.HasOne("HowTo.Entities.UserInfo.UserUniqueInfoDto", null)
                        .WithMany("LastChoiceOfAnswers")
                        .HasForeignKey("UserUniqueInfoDtoId");
                });

            modelBuilder.Entity("HowTo.Entities.UserInfo.LastInteractiveInfo.LastProgramWritingDto", b =>
                {
                    b.HasOne("HowTo.Entities.UserInfo.UserUniqueInfoDto", null)
                        .WithMany("LastProgramWritings")
                        .HasForeignKey("UserUniqueInfoDtoId");
                });

            modelBuilder.Entity("HowTo.Entities.UserInfo.LastInteractiveInfo.LastWritingOfAnswerDto", b =>
                {
                    b.HasOne("HowTo.Entities.UserInfo.UserUniqueInfoDto", null)
                        .WithMany("LastWritingOfAnswers")
                        .HasForeignKey("UserUniqueInfoDtoId");
                });

            modelBuilder.Entity("HowTo.Entities.ViewedEntity.ViewedEntity", b =>
                {
                    b.HasOne("HowTo.Entities.UserInfo.UserUniqueInfoDto", null)
                        .WithMany("ApprovedViewArticleIds")
                        .HasForeignKey("UserUniqueInfoDtoId");
                });

            modelBuilder.Entity("HowTo.Entities.Views.UserGuid", b =>
                {
                    b.HasOne("HowTo.Entities.Views.ViewDto", null)
                        .WithMany("Viewers")
                        .HasForeignKey("ViewDtoCourseId", "ViewDtoArticleId");
                });

            modelBuilder.Entity("HowTo.Entities.Course.CourseDto", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("HowTo.Entities.UserInfo.UserUniqueInfoDto", b =>
                {
                    b.Navigation("ApprovedViewArticleIds");

                    b.Navigation("LastCheckLists");

                    b.Navigation("LastChoiceOfAnswers");

                    b.Navigation("LastProgramWritings");

                    b.Navigation("LastWritingOfAnswers");
                });

            modelBuilder.Entity("HowTo.Entities.Views.ViewDto", b =>
                {
                    b.Navigation("Viewers");
                });
#pragma warning restore 612, 618
        }
    }
}
